name: print-pdf
on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install weasyprint
      - run: sudo apt install pandoc
      - run: weasyprint -v
